apiVersion: v1
kind: Service
metadata:
  name: {{ include "hugo-webhook.fullname" . }}
  labels:
    {{- include "hugo-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000  
      name: hook
      protocol: TCP
      targetPort: 9000
  selector:
    {{- include "hugo-webhook.selectorLabels" . | nindent 4 }}